Base.@kwdef struct BCVectors{T}
    yM::Vector{T} = T[]
    y_p::Vector{T} = T[]

    yAu_ux::Vector{T} = T[]
    yAu_uy::Vector{T} = T[]
    yAu_uz::Vector{T} = T[]
    yAv_vx::Vector{T} = T[]
    yAv_vy::Vector{T} = T[]
    yAv_vz::Vector{T} = T[]
    yAw_wx::Vector{T} = T[]
    yAw_wy::Vector{T} = T[]
    yAw_wz::Vector{T} = T[]

    yDiff::Vector{T} = T[]

    yIu_ux::Vector{T} = T[]
    yIv_uy::Vector{T} = T[]
    yIw_uz::Vector{T} = T[]
    yIu_vx::Vector{T} = T[]
    yIv_vy::Vector{T} = T[]
    yIw_vz::Vector{T} = T[]
    yIu_wx::Vector{T} = T[]
    yIv_wy::Vector{T} = T[]
    yIw_wz::Vector{T} = T[]

    ySu_ux::Vector{T} = T[]
    ySu_uy::Vector{T} = T[]
    ySu_uz::Vector{T} = T[]
    ySu_vx::Vector{T} = T[]
    ySu_wx::Vector{T} = T[]

    ySv_vx::Vector{T} = T[]
    ySv_vy::Vector{T} = T[]
    ySv_vz::Vector{T} = T[]
    ySv_uy::Vector{T} = T[]
    ySv_wy::Vector{T} = T[]

    ySw_wx::Vector{T} = T[]
    ySw_wy::Vector{T} = T[]
    ySw_wz::Vector{T} = T[]
    ySw_uz::Vector{T} = T[]
    ySw_vz::Vector{T} = T[]

    ydM::Vector{T} = T[]

    yAν_ux::Vector{T} = T[]
    yAν_uy::Vector{T} = T[]
    yAν_uz::Vector{T} = T[]
    yAν_vx::Vector{T} = T[]
    yAν_vy::Vector{T} = T[]
    yAν_vz::Vector{T} = T[]
    yAν_wx::Vector{T} = T[]
    yAν_wy::Vector{T} = T[]
    yAν_wz::Vector{T} = T[]

    yCux_k::Vector{T} = T[]
    yCuy_k::Vector{T} = T[]
    yCuz_k::Vector{T} = T[]
    yCvx_k::Vector{T} = T[]
    yCvy_k::Vector{T} = T[]
    yCvz_k::Vector{T} = T[]
    yCwx_k::Vector{T} = T[]
    yCwy_k::Vector{T} = T[]
    yCwz_k::Vector{T} = T[]

    yAuy_k::Vector{T} = T[]
    yAuz_k::Vector{T} = T[]
    yAvx_k::Vector{T} = T[]
    yAvz_k::Vector{T} = T[]
    yAwx_k::Vector{T} = T[]
    yAwy_k::Vector{T} = T[]

    yDiffu_f::Vector{T} = T[]
    yDiffv_f::Vector{T} = T[]
    yDiffw_f::Vector{T} = T[]

    yIu_ux3::Vector{T} = T[]
    yIv_uy3::Vector{T} = T[]
    yIu_vx3::Vector{T} = T[]
    yIv_vy3::Vector{T} = T[]

    yAu_ux3::Vector{T} = T[]
    yAu_uy3::Vector{T} = T[]
    yAv_vx3::Vector{T} = T[]
    yAv_vy3::Vector{T} = T[]
end
